version: '3.8'

services:
  go-language-course:
    build: ./.docker/go
    command: ./main.go
    ports:
      - 8000:8000
      - depends_on:
          - db
        environment:
          - DB_PASSWORD

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - DB_PASSWORD
    ports:
    - 5436:5432